[장승진]5/12 로또
campus-devil1032/campus-lotto-machine pull request #9
Opened 2023-05-12 05:59 UTC by jsj102

#기능
-로또(자동) 한게임당 최대 100매
-당첨금 지급
-한 게임 수익률
-게임 티켓당 당첨콘솔

#미구현
-당첨 통계 콘솔
-로또(수동)발급
-

#개션가능사항
-TreeSet 제대로사용하기
-진행,종료커맨드콘솔

2023-05-15 07:10 UTC, campus-devil1032 commented
5/15
## 기능
- 로또(자동) 한게임당 최대 100매
- 당첨금 지급
- 한 게임 수익률
- 게임 티켓당 당첨콘솔
- 당첨 통계 콘솔

## 미구현
- 로또(수동)발급

## 개선가능사항
- TreeSet 제대로사용하기
- 진행,종료커맨드콘솔

## 궁금증 이중배열구조를 활용해서
로토 티켓에 몇번째 티켓인지와 티켓의 공(숫자)번호를 저장했었는데,
트리셋구조로만 온전히 활용하려면 트리셋의 배열? 을 활용하는게 가장 좋을것 같은데
트리셋의 배열에 관한 내용은 찾을수 없어서
어떻게 사용할수 있을지 궁금합니다.
또 사용하지 못한다면, 어떤방식으로 바꾸는게 가장 이상적일지 궁금합니다.

2023-05-15 07:53 UTC, campus-devil1032 requested changes

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +//////////////////////////////treeset.retainAll() 좋은기능!!!
주석으로 코드의 시작과 끝을 코드로 명시해주는 것도 좋습니다.

```java
// LottoGame Start
// TODO: TreeSet활용 코드 뜯어고치기
public class LottoGame {
	public static void main(String[] args) {
		GameController.run();
	}

}

// LottoGame End
// TODO:  treeset.retainAll() 좋은기능!!!

```

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
MVC는 관심사분리, 의존성최소화를 위해서 적용하는 패턴입니다.

`public` 제한자를 class에 포함시키면 같은 패키지 안에서는 언제든지 클래스를 `import`를 통해 호출 할 수 있습니다.

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		LottoModel l = new LottoModel();
변수명은 가급적 의미있게 역할을 명시해주세요!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +			ConsolViewer.menu();
가급적 클래스 자체로 접근하지 마시고 static은 언제 어떤 상황에서 써야하는지 정확하게 한번 의도 파악 해보시는 게 좋을 것 같습니다.
MVC 각각의 레이어를 객체로 만들어서 접근해보시기 바랍니다

static은 들불처럼 번져요!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +			case 1: {
enum 을 통해서 코드에 의도를 명확하게 녹여보세요

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +			}
이 부분은 early exit 통해서 else 문을 없애보세요~

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +			}
안쓰이는 블럭은 굳이 필요 없습니다. 삭제!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +	}
code block의 깊이가 깊어져서 보기가 힘들다면 중괄호 끝나는 부분에 주석으로 명기하는 것도 좋습니다.

```
     } // end -- run()  
} // end -- GameContoller
```

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +	}
뷰어의 역할을 잘 정의 하셨습니다!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +	private final static int COLLECT_NUMBER_SIX_REWARD = 2000000000;// 당첨금액6개
매직넘버는 이처럼 스크리밍 케이스로 작성하셔야 합니다
아주 잘하셨어요 😃

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +	public void ticketMaker(Player p) throws IOException { // 티켓구매#0
함수명은 동사로 시작하는게 좋습니다
단일 책임 원칙을 준수하게끔 만드는데 도움이 됩니다

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		BufferedReader bfrd = new BufferedReader(new InputStreamReader(System.in));
이 코드는 컨트롤러에서 유저의 입력을 받는 메서드를 만들어서 작동하게끔 비즈니스 로직을 분리해보세요

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		BufferedReader bfrd = new BufferedReader(new InputStreamReader(System.in));
프로그램 전반에 걸쳐서 매번 나오는 기능은 공통 모듈로 따로 빼서 (ex. 유틸패키지) 호출 하게끔 만들면 재사용성과 예외처리 같은 일련의 행동들을 일관성있게 유지할 수 있습니다.

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		if (p.getPlayerMoney() < 1000) {
변수명은 명확하게!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		for (; true;) {
watchDog 이라는 개념을 한번 추가적으로 공부해보시는걸 추천드립니다~

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		}
else문을 없앨 수 있습니다. 한번 고민해보세요!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +	public void winnerChecker(Player p) { // 티켓비교#3
메서드의 주석은 javadoc을 이용해보시는걸 추천드립니다.

```java
        /**
           * 티켓비교#3
           * @param Player p - 블라블라~
	public void winnerChecker(Player p) {

        ...
        }
```

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		int collectCount = 0;// 일치갯수
오토 포멧팅 기능 잘 이용해주세요!
다른 팀원이 개발 할 때 본인이 개발하지 않은 부분까지도 불필요하게 수정 사항으로 포함되서 섞여 나가는 경우가 생깁니다.

```
int collectCount = 0;// 일치갯수
```

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +				for (int k = 0; k < 6; k++) {
계산로직의 깊이가 (=depth가) 깊어질 수록 그 동작방식을 코드에 정확히 명기해주셔야 합니다!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		int checkery = 0;
카멜케이스를 준수하게 된다면 아래처럼 될 것이에요
```java
int checkerX = 0;
int checkerY = 0;
```

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +
비즈니스 로직에는 동작방식을 간결하게 기술해주시는게 좋습니다

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +	 */
안쓰는 코드는 삭제하셔도 됩니다!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +	 */
혹은 필요한거라면 TODO로 정확하게 작업 내용을 명기해주세요

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +				}
if 문의 조건을 early exit 스타일로 한번 작성해보세요~

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +		case 3: {
enum을 통해서 이 상수값이 어떤 의미를 가지고 있는지 표시!

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +			}
validation 함수로 뽑아 낼 수 있어 보입니다.
```java
is3rdWinner();
is2ndWinner();
```

2023-05-15 07:53 UTC, campus-devil1032 commented on src/LottoGame.java
> +class Player { //controller
이 부분의 멤버를 보니까 DTO 혹은 VO 의 성격으로 보입니다.

성격을 명확하게 하시는게 좋습니다 :)

2023-05-16 00:49 UTC, jsj102 commented on src/LottoGame.java
> +class Player { //controller
어제 쭉 읽고 확인해보니 DTO가 맞았습니다. 설계하면서 controller로 사용할까 해서 주석 달아두고 controller를 따로 만들었는데 주석 제거 하는것을 잊었네요..

2023-05-16 00:50 UTC, jsj102 commented on src/LottoGame.java
> +	 */
삭제 완료했습니다!

2023-05-16 01:13 UTC, jsj102 commented on src/LottoGame.java
> +			}
isBonusCollect라는 early exit 형태로 만들어본 함수로 바꿨습니다.

2023-05-16 01:22 UTC, jsj102 commented on src/LottoGame.java
클래스 단위별로 쪼개 보았습니다.
메인부분인 LottoGame에서 GameController를 호출하여 로토게임 실행만 담당하고
GameController에서 ConsolViewer와 LottoModel을 호출하여 게임을 진행하거나 당첨콘솔확인, 프로그램 종료를 담당합니다.

2023-05-16 01:27 UTC, jsj102 commented on src/LottoGame.java
> +			ConsolViewer.menu();
static은 메인함수와 매직 넘버와 isInteger함수에서만 사용하도록 변경하였습니다.

2025-07-09 07:03 UTC, closed without merging